### ISSUE TITLE
plugin do not work in Eclipse version:Oxygen.1a Release (4.7.1a)

### ISSUE THREAD

**Issue by llade** [cnfree/Eclipse-Class-Decompiler#37]
**eclipse version info:**

Eclipse Java EE IDE for Web Developers.

Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

**stack:**

java.lang.NoSuchMethodError: org.eclipse.jdt.internal.core.SourceMapper.mapSource(Lorg/eclipse/jdt/core/IType;[CLorg/eclipse/jdt/internal/compiler/env/IBinaryType;)V
	at org.sf.feeling.decompiler.util.DecompileUtil.updateSourceRanges(DecompileUtil.java:176)
	at org.sf.feeling.decompiler.util.DecompileUtil.checkAndUpdateCopyright(DecompileUtil.java:119)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doOpenBuffer(JavaDecompilerClassFileEditor.java:228)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doOpenBuffer(JavaDecompilerClassFileEditor.java:151)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doOpenBuffer(JavaDecompilerClassFileEditor.java:143)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doSetInput(JavaDecompilerClassFileEditor.java:525)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:362)

**Comment by RobertZenz** [comment]
Duplicate of #36.

**Comment by bjmi** [comment]
Bug is not fixed in #36  but issue is closed.

**Comment by lxbzmy** [comment]
I saw folk https://github.com/listen1984/Eclipse-Class-Decompiler trying to fix the problem.

**Comment by janhvh** [comment]
Thanks guys at https://github.com/listen1984/Eclipse-Class-Decompiler !
Can confirm that this fixes the issue! ( #36 mentioned did not fix it for me).
Seems also to fix the issue that code completion / code assist did not work well anymore for me in Eclipse Oxygen (exceptions, error, showing only 3 or 4 out of 20+ methods/properties, etc).
